services:
  portainer:
    image: portainer/portainer-ce:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  portainer_agent_network:
    external: true
