Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder "./shared_token", "/vagrant/shared_token"
  config.vm.boot_timeout = 600
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096  # 4 ГБ памяти для каждой ВМ
    vb.cpus = 4
  end

  config.vm.define "manager01" do |manager|
    manager.vm.hostname = "manager01"
    manager.vm.synced_folder ".",  "/home/vagrant/webservice/"
    manager.vm.network "private_network", ip: "192.168.56.10"
    manager.vm.network "forwarded_port", guest: 81, host: 8081
    manager.vm.network "forwarded_port", guest: 87, host: 8087
    manager.vm.network "forwarded_port", guest: 9000, host: 90
    manager.vm.network "forwarded_port", guest: 9001, host: 9001
    manager.vm.provision "shell", path: "scripts/install_docker.sh"
    manager.vm.provision "shell", path: "scripts/init_swarm.sh"
  end

  config.vm.define "worker01" do |worker|
    worker.vm.hostname = "worker01"
    worker.vm.network "private_network", ip: "192.168.56.11"
    worker.vm.provision "shell", path: "scripts/install_docker.sh"
    worker.vm.provision "shell", path: "scripts/join_swarm.sh"
  end

  config.vm.define "worker02" do |worker|
    worker.vm.hostname = "worker02"
    worker.vm.network "private_network", ip: "192.168.56.12"
    worker.vm.provision "shell", path: "scripts/install_docker.sh"
    worker.vm.provision "shell", path: "scripts/join_swarm.sh"
  end
end
