apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yml
  - secret.yml

patches:
  - path: replicas-patch.yml
    target:
      kind: Deployment
      name: gateway-service
