Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096  # 4 ГБ памяти для каждой ВМ
    vb.cpus = 4
  end

    config.vm.define "manager" do |manager|
      manager.vm.hostname = "manager"
      manager.vm.network "private_network", ip: "192.168.56.10"
      manager.vm.network "forwarded_port", guest: 8500, host: 8500
    end
  
    config.vm.define "consul_server" do |server|
      server.vm.hostname = "consul-server"
      server.vm.network "private_network", ip: "192.168.56.11"
    end
  
    config.vm.define "api" do |api|
      api.vm.hostname = "api"
      api.vm.network "private_network", ip: "192.168.56.12"
      api.vm.network "forwarded_port", guest: 8082, host: 8082
    end

    config.vm.define "db" do |db|
      db.vm.hostname = "db"
      db.vm.network "private_network", ip: "192.168.56.13"
    end
  end 
  
  