---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: corazono/postgres:1.0
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_PORT
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
       - name: postgres-storage
         persistentVolumeClaim:
            claimName: postgres-pvc  
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:latest  
          env:
            - name: RABBIT_MQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBIT_MQ_HOST
            - name: RABBIT_MQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBIT_MQ_PORT
            - name: RABBIT_MQ_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBIT_MQ_QUEUE_NAME
            - name: RABBIT_MQ_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBIT_MQ_EXCHANGE
            - name: RABBITMQ_MQ_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBIT_MQ_USER
            - name: RABBITMQ_MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBIT_MQ_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      name: amqp
  selector:
    app: rabbitmq

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  labels:
    app: app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: corazono/src-booking-service:1.0
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB

            - name: RABBIT_MQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBIT_MQ_HOST
            - name: RABBIT_MQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBIT_MQ_PORT
            - name: RABBIT_MQ_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBIT_MQ_QUEUE_NAME
            - name: RABBIT_MQ_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBIT_MQ_EXCHANGE

            - name: HOTEL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: HOTEL_SERVICE_HOST
            - name: HOTEL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: HOTEL_SERVICE_PORT

            - name: PAYMENT_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PAYMENT_SERVICE_HOST
            - name: PAYMENT_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PAYMENT_SERVICE_PORT

            - name: LOYALTY_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOYALTY_SERVICE_HOST
            - name: LOYALTY_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOYALTY_SERVICE_PORT

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: RABBIT_MQ_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBIT_MQ_USER
            - name: RABBIT_MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBIT_MQ_PASSWORD
            - name: GATEWAY_SERVICE_UUID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: GATEWAY_SERVICE_UUID
            - name: BOOKING_SERVICE_UUID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: BOOKING_SERVICE_UUID

---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
spec: 
  type: ClusterIP
  ports: 
    - port: 8083
      targetPort: 8083
  selector:
    app: booking-service

--- 

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: gateway-service
  labels:
    app: app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: corazono/src-gateway-service:1.0
          env:
            - name: SESSION_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SESSION_SERVICE_HOST
            - name: SESSION_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SESSION_SERVICE_PORT

            - name: HOTEL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: HOTEL_SERVICE_HOST
            - name: HOTEL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: HOTEL_SERVICE_PORT

            - name: BOOKING_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BOOKING_SERVICE_HOST
            - name: BOOKING_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BOOKING_SERVICE_PORT

            - name: PAYMENT_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PAYMENT_SERVICE_HOST
            - name: PAYMENT_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PAYMENT_SERVICE_PORT

            - name: LOYALTY_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOYALTY_SERVICE_HOST
            - name: LOYALTY_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: LOYALTY_SERVICE_PORT

            - name: REPORT_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REPORT_SERVICE_HOST
            - name: REPORT_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REPORT_SERVICE_PORT  
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: ClusterIP       
  selector:
    app: gateway-service
  ports:
    - port: 8087        
      targetPort: 8087  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-service
  labels:
    app: app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-service
  template:
    metadata:
      labels:
        app: hotel-service
    spec:
      containers:
        - name: hotel-service
          image: corazono/src-hotel-service:1.0
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_PORT
---
apiVersion: v1
kind: Service
metadata: 
  name: hotel-service
spec:
  type: ClusterIP
  selector:
    app: hotel-service
  ports:
    - port: 8082
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata: 
   name: loyalty-service
   labels:
    app: app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-service
  template:
    metadata:
      labels:
        app: loyalty-service
    spec: 
      containers: 
        - name: loyalty-service
          image: corazono/src-loyalty-service:1.0
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: loyalty-service
spec:
  type: ClusterIP
  selector:
    app: loyalty-service
  ports:
    - port: 8085
      targetPort: 8085
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
   name: payment-service
   labels:
    app: app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec: 
      containers: 
        - name: payment-service
          image: corazono/src-payment-service:1.0
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_PORT
---
apiVersion: v1
kind: Service
metadata: 
  name: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - port: 8084
      targetPort: 8084
---
apiVersion: apps/v1
kind: Deployment
metadata: 
   name: report-service
   labels:
    app: app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
    spec: 
      containers: 
        - name: report-service
          image: corazono/src-report-service:1.0
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_PORT
            - name: RABBIT_MQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBIT_MQ_HOST
            - name: RABBIT_MQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBIT_MQ_PORT
            - name: RABBIT_MQ_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBIT_MQ_QUEUE_NAME
            - name: RABBIT_MQ_EXCHANGE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RABBIT_MQ_EXCHANGE
            - name: RABBIT_MQ_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBIT_MQ_USER
            - name: RABBIT_MQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBIT_MQ_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: report-service
spec:
  type: ClusterIP
  selector:
    app: report-service
  ports:
    - port: 8086
      targetPort: 8086
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
   name: session-service
   labels:
    app: app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-service
  template:
    metadata:
      labels:
        app: session-service
    spec: 
      containers: 
        - name: session-service
          image: corazono/src-session-service:1.0
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_PORT
---
apiVersion: v1
kind: Service
metadata: 
  name: session-service
spec:
  type: ClusterIP
  selector:
    app: session-service
  ports:
    - port: 8081
      targetPort: 8081