apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "reservations_db"

  RABBIT_MQ_HOST: "rabbitmq"
  RABBIT_MQ_PORT: "5672"
  RABBIT_MQ_QUEUE_NAME: "messagequeue"
  RABBIT_MQ_EXCHANGE: "messagequeue-exchange"
  
  GATEWAY_SERVICE_HOST: "gateway-service"
  GATEWAY_SERVICE_PORT: "8087"
  SESSION_SERVICE_HOST: "session-service"
  SESSION_SERVICE_PORT: "8081"
  HOTEL_SERVICE_HOST: "hotel-service"
  HOTEL_SERVICE_PORT: "8082"
  BOOKING_SERVICE_HOST: "booking-service"
  BOOKING_SERVICE_PORT: "8083"
  PAYMENT_SERVICE_HOST: "payment-service"
  PAYMENT_SERVICE_PORT: "8084"
  LOYALTY_SERVICE_HOST: "loyalty-service"
  LOYALTY_SERVICE_PORT: "8085"
  REPORT_SERVICE_HOST: "report-service"
  REPORT_SERVICE_PORT: "8086"
