{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "app logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"app-logs\"} |= ``"
    }
   ]
  },
  {
   "title": "service requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_consumed_total{job=\"application-services\", name=\"rabbit\"})\r\n",
     "legendFormat": "rabbitmq consumed"
    },
    {
     "expr": "sum(rabbitmq_published_total{job=\"application-services\", name=\"rabbit\"})\r\n\r\n",
     "legendFormat": "rabbitmq published"
    },
    {
     "expr": "http_server_requests_seconds_count{exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/api/v1/gateway/hotels\",}\r\n",
     "legendFormat": "bookings"
    },
    {
     "expr": "sum(http_server_requests_seconds_count{uri=~\"/api/v1/gateway/.*\"})\r\n\r\n",
     "legendFormat": "gateways"
    },
    {
     "expr": "http_server_requests_seconds_count{exception=\"None\",method=\"GET\",outcome=\"SUCCESS\",status=\"200\",uri=\"/api/v1/auth/authorize\",}",
     "legendFormat": "authorizations"
    }
   ]
  },
  {
   "title": "RAM free/used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes) / 1024 / 1024 / 1024\r\n",
     "legendFormat": "RAM free {{instance}}"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 / 1024\r\n",
     "legendFormat": "RAM used {{instance}}"
    }
   ]
  },
  {
   "title": "RAM by services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_swarm_service_name) (\r\n  container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"mystack_.*\"}\r\n) / 1024 / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU by nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "100 - (\r\n  avg by (instance) (\r\n    rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\r\n  ) * 100\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "СPU by cores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "100 - (\r\n  avg by (instance, cpu) (\r\n    rate(node_cpu_seconds_total{mode=\"idle\"}[5m])\r\n  ) * 100\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "СPU by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_swarm_service_name) (\r\n  rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\"mystack_.*\"}[5m])\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster info",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (instance) (up{job=\"node_exporter\"}))\r\n",
     "legendFormat": "node"
    },
    {
     "expr": "count(\r\n  count_over_time(container_last_seen{container_label_com_docker_swarm_service_name!=\"\"}[30s])\r\n)\r\n",
     "legendFormat": "containers"
    },
    {
     "expr": "count(count by (container_label_com_docker_stack_namespace) \r\n  (container_cpu_usage_seconds_total{container_label_com_docker_stack_namespace!=\"\"})\r\n) \r\n",
     "legendFormat": "stack"
    },
    {
     "expr": "sum(count(node_cpu_seconds_total{mode=\"idle\"}) by (instance))\r\n\r\n\r\n",
     "legendFormat": "CPU"
    },
    {
     "expr": "probe_success{instance=\"http://google.com\", job=\"blackbox_exporter\"}",
     "legendFormat": "google.com 1-yes"
    }
   ]
  }
 ]
}