- name: Downloading dependencies
  apt:
    name:
      - unzip
      - curl
    state: present
    update_cache: yes
  become: yes

- name: Downloading consul file
  get_url:
        url: "https://releases.hashicorp.com/consul/1.14.0/consul_1.14.0_linux_amd64.zip"
        dest: /tmp/consul.zip
        mode: '0644'
  become: yes

- name: Unarchiving a consul zip file
  unarchive:
    src: /tmp/consul.zip
    dest: /usr/local/bin/
    remote_src: yes
    mode: '0755'
  become: yes
- name: Checking that Consul is installed
  command: consul --version
  changed_when: false
  become: yes

- name: Creating a user for Consul
  user:
     name: consul
     system: yes
     shell: /bin/false
  become: yes

- name: Creating a directory for configurations
  file:
     path: /etc/consul.d
     state: directory
     owner: consul
     group: consul
     mode: '0755'
  become: yes

- name: Create data directory for Consul
  file:
    path: /var/lib/consul
    state: directory
    owner: consul
    group: consul
    mode: '0755'
  become: yes


- name: copy consul_client.hcl
  become: yes
  copy:
    src: consul_client.hcl
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: '0644'

- name: Create systemd unit file for Consul
  become: yes
  copy:
    dest: /etc/systemd/system/consul.service
    content: |
      [Unit]
      Description=Consul Agent
      Requires=network-online.target
      After=network-online.target

      [Service]
      User=consul
      Group=consul
      ExecStart=/usr/local/bin/consul agent -config-dir=/etc/consul.d
      ExecReload=/bin/kill -HUP $MAINPID
      KillMode=process
      KillSignal=SIGTERM
      Restart=on-failure
      LimitNOFILE=65536

      [Install]
      WantedBy=multi-user.target

- name: Copy Consul service definition of postgres
  copy:
    src: postgres_service.json
    dest: /etc/consul.d/postgres_service.json
    owner: consul
    group: consul
    mode: '0644'
  become: yes
  when: "'db' in group_names"

- name: Copy Consul service definition of hotels_service
  copy:
     src: hotels_service.json
     dest: /etc/consul.d/hotels_service.json
     owner: consul
     group: consul
     mode: '0644'
  become: yes
  when: "'api' in group_names"

- name: Reload systemd
  command: systemctl daemon-reload
  become: yes

- name: Restart Consul
  systemd:
    name: consul
    state: restarted
  become: yes

- name: Starting Consul
  systemd:
    name: consul
    state: started
    enabled: yes
  become: yes

- name: Download envoy signing key and convert to GPG
  shell: |
    wget -qO - https://apt.envoyproxy.io/signing.key | gpg --dearmor -o /etc/apt/keyrings/envoy-keyring.gpg
  args:
    creates: /etc/apt/keyrings/envoy-keyring.gpg
  become: yes

- name: Adding Envoy to repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/envoy-keyring.gpg] https://apt.envoyproxy.io jammy main"
    filename: envoy
    state: present

- name: Downloading envoy
  apt:
     name: envoy
     state: present
     update_cache: yes
  become: yes

- name: Create Envoy systemd unit (for db)
  template:
    src: envoy-db.service.j2
    dest: /etc/systemd/system/envoy.service
  when: "'db' in group_names"
  become: yes

- name: Create Envoy systemd unit (for api)
  template:
    src: envoy-api.service.j2
    dest: /etc/systemd/system/envoy.service
  when: "'api' in group_names"
  become: yes

- name: Reload systemd
  become: yes
  command: systemctl daemon-reload

- name: Enable and start services
  become: yes
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - consul
    - envoy
