global:
  resolve_timeout: 5m

route:
  receiver: 'telegram'
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: "8330306224:AAEpHOIZmRF7E7a-2KAEStrFNGh_l3B8S1w"
        chat_id: 340939094