services:
  postgres:
    image: corazono/postgres:1.0
    deploy:
      placement:
        constraints:
          - node.role == worker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data  
    networks:
      - overlay_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    deploy:
      placement:
        constraints:
          - node.role == worker
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "15692:15692"   # для Prometheus
    networks:
      - overlay_net


  session-service:
    image: corazono/src-session-service:1.0
    deploy:
      placement:
        constraints:
          - node.role == worker
    ports:
      - 8081:8081
    depends_on:
      - postgres
    networks:
      - overlay_net
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db

  hotel-service:
    image: corazono/src-hotel-service:1.0
    deploy:
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotels_db
    networks:
      - overlay_net

  booking-service:
    image: corazono/src-booking-service:1.0
    deploy:
      placement:
        constraints:
          - node.role == worker
    ports:
      - 8083:8083
    depends_on:
      - postgres
      - rabbitmq
      - hotel-service
      - payment-service
      - loyalty-service
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservations_db

      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange

      HOTEL_SERVICE_HOST: hotel-service
      HOTEL_SERVICE_PORT: 8082
      PAYMENT_SERVICE_HOST: payment-service
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty-service
      LOYALTY_SERVICE_PORT: 8085
    networks:
      - overlay_net

  payment-service:
    image: corazono/src-payment-service:1.0
    deploy:
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments_db
    networks:
      - overlay_net

  loyalty-service:
    image: corazono/src-loyalty-service:1.0
    deploy:
      placement:
        constraints:
          - node.role == worker
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balances_db
    networks:
      - overlay_net

  report-service:
    image: corazono/src-report-service:1.0
    deploy:
      placement:
        constraints:
          - node.role == worker
    ports:
      - 8086:8086
    depends_on:
      - postgres
      - rabbitmq
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statistics_db

      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
    networks:
      - overlay_net

  gateway-service:
    image: corazono/src-gateway-service:1.0
    deploy:
      placement:
        constraints:
          - node.role == worker
    ports:
      - 8087:8087
    depends_on:
      - session-service
      - hotel-service
      - booking-service
      - payment-service
      - loyalty-service
      - report-service
    networks:
      - overlay_net
    environment:
      SESSION_SERVICE_HOST: session-service
      SESSION_SERVICE_PORT: 8081
      HOTEL_SERVICE_HOST: hotel-service
      HOTEL_SERVICE_PORT: 8082
      BOOKING_SERVICE_HOST: booking-service
      BOOKING_SERVICE_PORT: 8083
      PAYMENT_SERVICE_HOST: payment-service
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty-service
      LOYALTY_SERVICE_PORT: 8085
      REPORT_SERVICE_HOST: report-service
      REPORT_SERVICE_PORT: 8086

networks:
  overlay_net:
    driver: overlay 
    attachable: true

volumes:
  pg_data:
    driver: local
