global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']  

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
     - targets: 
        - '192.168.56.10:9090'
        - '192.168.56.11:9090'
        - '192.168.56.12:9090'
  - job_name: 'application-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - '192.168.56.10:8081' # session-service
          - '192.168.56.10:8083' # booking-servic
          - '192.168.56.10:8086' # report-service
          - '192.168.56.10:8087' # gateway-service

  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://google.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['192.168.56.10:9100', '192.168.56.11:9100', '192.168.56.12:9100']
  
  - job_name: 'cadvisor'
    static_configs:
    - targets: ['192.168.56.10:8080', '192.168.56.11:8080', '192.168.56.12:8080']
  
  - job_name: 'loki'
    static_configs:
      - targets:
          - '192.168.56.10:3100'
