server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    tenant_id: 1

scrape_configs:
  - job_name: app-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: ['__meta_docker_container_label_com_docker_swarm_service_name']
        target_label: service

      - source_labels: ['__meta_docker_container_name']
        target_label: container

      - target_label: job
        replacement: 'app-logs'

      - target_label: __path__
        replacement: /var/lib/docker/containers/*/*.log
