{{- range $service, $config := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service }}
  labels:
    {{- include "myapp.labels" $ | nindent 4 }}
spec:
  {{- if not $.Values.autoscaling.enabled }}
  replicas: {{ $config.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ $service }}
  template:
    metadata:
      labels:
        app: {{ $service }}
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with $.Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $service }}
          image: "{{ $config.image.repository }}:{{ $config.image.tag | default $.Chart.AppVersion }}"
          {{- with $config.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $config.env }}
          env:
            {{- range $key, $val := . }}
            - name: {{ $key }}
              {{- if $val.secretKeyRef }}
              valueFrom:
                secretKeyRef:
                  name: {{ $config.secretName }}
                  key: {{ $val.secretKeyRef }}
              {{- else if $val.configMapKeyRef }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $config.configName }}
                  key: {{ $val.configMapKeyRef.key }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- with $config.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with $config.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
