Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096  # 4 ГБ памяти для каждой ВМ
    vb.cpus = 4
  end

  config.vm.define "manager" do |manager|
    manager.vm.hostname = "manager"
    manager.vm.network "private_network", ip: "192.168.56.10"

  end
  config.vm.define "node01" do |worker|
    worker.vm.hostname = "node01"
    worker.vm.network "private_network", ip: "192.168.56.11"
    worker.vm.network "forwarded_port", guest: 8081, host: 8081
    worker.vm.network "forwarded_port", guest: 8087, host: 8087
  end
  config.vm.define "node02" do |worker|
    worker.vm.hostname = "node02"
    worker.vm.network "private_network", ip: "192.168.56.12"
    worker.vm.network "forwarded_port", guest: 80, host: 8080
  end
end
